### ISSUE TITLE
properties sonar.test and sonar.sources cannot be changed

### ISSUE THREAD

**Issue by lupenium** [mdasberg/grunt-karma-sonar#26]
these properties has hardcoded in the code, with values: test and src respectively

**Comment by lupenium** [comment]
any reason for this behavior?

**Comment by mdasberg** [comment]
To be able to support multiple paths and merge multiple sources and tests, all the files need to be copied in order to be processed. They will be copied to output dir.

Your project can of course contain multiple paths with different source and test folders like this:

```js
paths: [
    {
        cwd: 'data/projectx',
        src: 'app',
        test: 'test',
        reports: {
            unit: 'results/karma/results.xml',
            coverage: 'results/karma/coverage/**/lcov.info',
            itCoverage: 'results/protractor-coverage/**/lcov.info'
        }
    },
    {
        cwd: 'data/projecty',
        src: 'src',
        test: 'some_other_dir',
        reports: {
            unit: 'results/karma/results.xml',
            coverage: 'results/karma/coverage/**/lcov.info'
        }
    }
]
```

Do you have a reason for this to be configurable?

**Comment by lupenium** [comment]
Thank you for the answer, I understood the concept, problem solved.
